<h1> Digital Device vs. Sleep Model </h1>

**Question:** Can we predict my quality of sleep from my device usage?

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

plt.style.use("fivethirtyeight")
sns.set_context("notebook")

In [41]:
import json

data = json.load(open('fb_data/sleep/sleep-2018-08-30.json', 'r'))
fb_htrt_test = pd.json_normalize(data)

In [42]:
fb_htrt_test

,logId,dateOfSleep,startTime,endTime,duration,minutesToFallAsleep,minutesAsleep,minutesAwake,minutesAfterWakeup,timeInBed,...,levels.summary.wake.count,levels.summary.wake.minutes,levels.summary.wake.thirtyDayAvgMinutes,levels.summary.light.count,levels.summary.light.minutes,levels.summary.light.thirtyDayAvgMinutes,levels.summary.rem.count,levels.summary.rem.minutes,levels.summary.rem.thirtyDayAvgMinutes,levels.shortData
0,19672669150,2018-09-29,2018-09-29T15:09:00.000,2018-09-29T17:42:30.000,9180000,0,150,3,0,153,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,19670111081,2018-09-29,2018-09-29T01:16:00.000,2018-09-29T07:58:00.000,24120000,0,365,37,0,402,...,21.0,37.0,50.0,21.0,203.0,217.0,5.0,100.0,89.0,"[{'dateTime': '2018-09-29T01:16:00.000', 'leve..."
2,19660398097,2018-09-28,2018-09-28T01:27:00.000,2018-09-28T07:37:30.000,22200000,0,309,61,0,370,...,22.0,61.0,49.0,24.0,180.0,219.0,6.0,57.0,90.0,"[{'dateTime': '2018-09-28T01:27:00.000', 'leve..."
3,19649903211,2018-09-27,2018-09-26T22:52:00.000,2018-09-27T08:46:30.000,35640000,0,541,53,0,594,...,40.0,53.0,49.0,36.0,259.0,217.0,14.0,166.0,87.0,"[{'dateTime': '2018-09-26T23:23:30.000', 'leve..."
4,19639676952,2018-09-26,2018-09-26T00:41:00.000,2018-09-26T07:36:30.000,24900000,0,376,39,0,415,...,25.0,39.0,50.0,20.0,141.0,220.0,12.0,108.0,87.0,"[{'dateTime': '2018-09-26T00:41:00.000', 'leve..."
5,19628671579,2018-09-25,2018-09-25T02:59:00.000,2018-09-25T10:16:00.000,26220000,0,399,38,0,437,...,32.0,38.0,50.0,34.0,245.0,219.0,5.0,104.0,86.0,"[{'dateTime': '2018-09-25T03:34:00.000', 'leve..."
6,19618359907,2018-09-24,2018-09-23T23:12:00.000,2018-09-24T07:08:00.000,28560000,0,410,66,0,476,...,18.0,66.0,49.0,21.0,257.0,218.0,6.0,77.0,86.0,"[{'dateTime': '2018-09-24T00:56:30.000', 'leve..."
7,19609729328,2018-09-23,2018-09-23T07:10:00.000,2018-09-23T11:22:30.000,15120000,0,222,30,0,252,...,16.0,30.0,50.0,14.0,136.0,221.0,6.0,43.0,88.0,"[{'dateTime': '2018-09-23T07:58:00.000', 'leve..."
8,19602100197,2018-09-22,2018-09-22T15:55:30.000,2018-09-22T18:26:30.000,9060000,0,139,12,0,151,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,19599671383,2018-09-22,2018-09-22T00:11:30.000,2018-09-22T09:47:30.000,34560000,0,506,70,0,576,...,43.0,70.0,49.0,40.0,313.0,217.0,12.0,112.0,87.0,"[{'dateTime': '2018-09-22T00:11:30.000', 'leve..."
10,19589146328,2018-09-21,2018-09-20T23:15:00.000,2018-09-21T07:19:00.000,29040000,0,408,76,0,484,...,27.0,76.0,48.0,29.0,248.0,215.0,7.0,77.0,88.0,"[{'dateTime': '2018-09-20T23:15:00.000', 'leve..."
11,19578204384,2018-09-20,2018-09-19T23:47:30.000,2018-09-20T08:49:30.000,32520000,0,474,68,0,542,...,31.0,68.0,47.0,30.0,260.0,213.0,9.0,130.0,85.0,"[{'dateTime': '2018-09-19T23:59:00.000', 'leve..."
12,19569843650,2018-09-19,2018-09-18T23:16:30.000,2018-09-19T07:27:30.000,29460000,0,434,57,0,491,...,35.0,57.0,46.0,34.0,276.0,209.0,7.0,98.0,85.0,"[{'dateTime': '2018-09-19T00:07:00.000', 'leve..."
13,19569843649,2018-09-18,2018-09-18T00:32:30.000,2018-09-18T07:42:30.000,25800000,0,392,38,1,430,...,37.0,38.0,47.0,27.0,243.0,207.0,13.0,96.0,84.0,"[{'dateTime': '2018-09-18T00:38:30.000', 'leve..."
14,19569843648,2018-09-17,2018-09-16T22:59:00.000,2018-09-17T07:31:00.000,30720000,0,447,65,0,512,...,35.0,65.0,45.0,31.0,272.0,202.0,12.0,90.0,83.0,"[{'dateTime': '2018-09-16T23:13:00.000', 'leve..."
15,19569843647,2018-09-16,2018-09-16T03:52:30.000,2018-09-16T09:00:00.000,18420000,0,268,39,0,307,...,19.0,39.0,46.0,20.0,169.0,205.0,3.0,46.0,86.0,"[{'dateTime': '2018-09-16T03:52:30.000', 'leve..."
16,19569843646,2018-09-15,2018-09-15T01:31:30.000,2018-09-15T09:47:30.000,29760000,0,444,52,0,496,...,32.0,52.0,45.0,28.0,210.0,204.0,10.0,128.0,83.0,"[{'dateTime': '2018-09-15T01:39:00.000', 'leve..."
17,19516453617,2018-09-14,2018-09-13T23:43:30.000,2018-09-14T07:12:00.000,26880000,0,398,50,0,448,...,30.0,50.0,45.0,28.0,244.0,201.0,6.0,102.0,81.0,"[{'dateTime': '2018-09-14T00:40:30.000', 'leve..."
18,19516453616,2018-09-13,2018-09-12T23:20:00.000,2018-09-13T07:31:30.000,29460000,0,430,61,0,491,...,32.0,61.0,44.0,35.0,221.0,199.0,8.0,104.0,79.0,"[{'dateTime': '2018-09-12T23:29:00.000', 'leve..."
19,19516453615,2018-09-12,2018-09-11T23:57:00.000,2018-09-12T07:24:30.000,26820000,0,393,54,0,447,...,21.0,54.0,43.0,21.0,199.0,199.0,6.0,120.0,75.0,"[{'dateTime': '2018-09-12T00:02:30.000', 'leve..."
20,19516453614,2018-09-11,2018-09-11T00:57:00.000,2018-09-11T07:41:30.000,24240000,0,353,51,0,404,...,31.0,51.0,42.0,32.0,215.0,198.0,3.0,66.0,76.0,"[{'dateTime': '2018-09-11T00:57:00.000', 'leve..."
21,19516453613,2018-09-10,2018-09-10T16:19:00.000,2018-09-10T18:04:00.000,6300000,0,96,9,0,105,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,19516453611,2018-09-10,2018-09-10T03:34:30.000,2018-09-10T07:19:30.000,13500000,0,195,30,1,225,...,15.0,30.0,43.0,16.0,135.0,206.0,2.0,27.0,82.0,"[{'dateTime': '2018-09-10T04:06:00.000', 'leve..."
23,19459051660,2018-09-09,2018-09-09T05:05:30.000,2018-09-09T11:36:30.000,23460000,0,353,38,0,391,...,28.0,38.0,44.0,25.0,203.0,206.0,7.0,89.0,81.0,"[{'dateTime': '2018-09-09T05:13:00.000', 'leve..."
24,19449995851,2018-09-08,2018-09-08T03:28:00.000,2018-09-08T09:55:30.000,23220000,0,338,49,0,387,...,22.0,49.0,43.0,20.0,174.0,211.0,8.0,88.0,80.0,"[{'dateTime': '2018-09-08T04:12:00.000', 'leve..."
25,19449995850,2018-09-07,2018-09-06T23:54:00.000,2018-09-07T07:12:00.000,26280000,0,395,43,0,438,...,25.0,43.0,43.0,23.0,234.0,207.0,6.0,91.0,78.0,"[{'dateTime': '2018-09-06T23:54:00.000', 'leve..."
26,19449995849,2018-09-06,2018-09-06T01:35:00.000,2018-09-06T08:37:00.000,25320000,0,380,42,0,422,...,29.0,42.0,43.0,22.0,165.0,217.0,11.0,114.0,69.0,"[{'dateTime': '2018-09-06T01:35:00.000', 'leve..."
27,19415726891,2018-09-05,2018-09-04T23:51:00.000,2018-09-05T07:16:30.000,26700000,0,389,56,0,445,...,25.0,56.0,39.0,23.0,235.0,211.0,8.0,94.0,61.0,"[{'dateTime': '2018-09-05T00:41:00.000', 'leve..."
28,19409007804,2018-09-04,2018-09-04T00:36:30.000,2018-09-04T07:39:00.000,25320000,0,371,51,0,422,...,38.0,51.0,33.0,33.0,206.0,214.0,10.0,71.0,56.0,"[{'dateTime': '2018-09-04T00:48:00.000', 'leve..."
29,19388539027,2018-09-02,2018-09-02T07:14:30.000,2018-09-02T14:55:30.000,27660000,0,422,39,0,461,...,24.0,39.0,26.0,27.0,300.0,127.0,6.0,58.0,53.0,"[{'dateTime': '2018-09-02T07:46:30.000', 'leve..."
30,19388539026,2018-09-01,2018-09-01T07:28:00.000,2018-09-01T11:11:30.000,13380000,0,197,26,0,223,...,15.0,26.0,0.0,13.0,127.0,0.0,4.0,53.0,0.0,"[{'dateTime': '2018-09-01T07:59:30.000', 'leve..."